Dockerfile

#3
도커 파일 작성
이미 push한 commit 수정하는 법

[FEAT/#3] 도커 파일 작성

---

lib/screens/Choose_screen.dart
lib/screens/Login_screen.dart
pubspec.lock
pubspec.yaml

toggle_switch 패키지 활용하여 해당 토클 선택할 수 있도록 구현
#8 
Toggle switch 패키지를 활용하여 해당 토글 선택할 수 있도록 구현

feat : 사장님 / 고객님 선택 화면 구현

---

lib/main.dart
lib/screens/Choose_screen.dart
lib/screens/Signup_screen.dart

formatEditUpdate 메서드와 문자열을 임시로 저장할 StringBuffer 생성 후 입력 값 자리 인덱스로 처리
해당 자리에 하이픈 추가
#10 
formatEditUpdate 메서드와 문자열을 임시로 저장할 StringBuffer 생성 후 입력 값 자리 인덱스로 처리
해당 자리에 하이픈 추가

[feat/#10] 회원 가입 화면 구현

---

lib/screens/home_screen.dart
lib/screens/reply_screen.dart
lib/screens/review_screen.dart
lib/widgets/userReview_widget.dart

#16
- 답글 버튼 누를 시 작성 페이지로 이동 기능 구현
- 작성 페이지에서 선택한 해당 리뷰에 나오게 구현
- 미답글 리뷰 선택 시 리뷰 답글에서 답글 버튼 나오게 수정

[Feat/#16] 답글 작성 화면 구현

---

lib/screens/filtering_screen.dart
lib/screens/reply_screen.dart
lib/screens/review_screen.dart
lib/widgets/userReview_widget.dart
pubspec.lock

#17
- 신고, 차단, 숨김을 Popupmenubutton을 사용해서 구현
- 차단 or 숨김 시 필터링 페이지에 차단 or 숨김 리뷰라고 올라오도록 구현

[Feat/#17] 더보기란에 있는 버튼과 연결되는 페이지 구현

---

Dockerfile
macos/Flutter/GeneratedPluginRegistrant.swift
pubspec.lock

#27
- /app/flutter_project를 /app/frontend로 변경
- 이유 : 우리 프로젝트 디렉토리로 이동해야하는데 다른 이름으로 지정

[Fix/#27] 도커파일 코드 수정

---

lib/owner/screens/signup_screen.dart
pubspec.lock
pubspec.yaml

#39
- request body가 수정돼 서버로 전송할 데이터들 수정
- memo => address로 수정

[Fix(common)/#39] 회원가입 api 수정

---

lib/user/screens/complete_screen.dart
lib/user/screens/write_screen.dart
pubspec.lock
pubspec.yaml

#60
- 평점 직접 설정할 수 있도록 PannableRatingBar 사용
- 텍스트폼필드를 여러줄 입력 가능
- 별점과 리뷰를 작성해야만 등록하기 버튼 활성화 구현
- 등록 버튼 누른 후 주문 내역 페이지에서 작성된 리뷰로 변경 구현
- null일 경우를 대비해서 isWritten 기본값을 설정
- imagePicker 사용
- 이미지 삭제 구현

[Feat(user)/#60] 리뷰 작성 페이지 구현

---

ios/Podfile.lock
ios/Runner.xcodeproj/project.pbxproj
ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
lib/user/screens/cart_screen.dart
lib/user/screens/complete_screen.dart
lib/user/screens/menuselect_screen.dart
lib/user/screens/userOrder_screen.dart
lib/user/screens/userReview_screen.dart
lib/user/screens/write_screen.dart
lib/user/widgets/cart_widget.dart
lib/user/widgets/orderAndPay_widget.dart
pubspec.lock
pubspec.yaml

#63
https://github.com/C-S-A-I-CommentScribeAI/frontend/assets/127868094/06f2f63b-591b-40a6-ad35-980d6c64965e

[Feat(user)/#63] 장바구니에 담는 기능 구현하기

---

ios/Runner.xcodeproj/project.pbxproj
ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
lib/owner/services/store_service.dart
lib/user/screens/menuselect_screen.dart
lib/user/screens/storeselect_screen.dart
lib/user/screens/userHome_screen.dart
lib/user/services/userStore_service.dart
lib/user/widgets/menuSearch_widget.dart

#72
- showSearch 위젯을 통해서 검색 창으로 이동 구현
- 모든 가게를 볼 수 있는 api를 연동 후 리스트에 저장
- 저장한 리스트로 검색 제안 시 보여줄 가게를 구현
- 검색 결과가 변경될 때마다 filteredStoreItems 업데이트
https://github.com/C-S-A-I-CommentScribeAI/frontend/assets/127868094/aeaac6ff-3dc6-4e30-8812-5a0c26dd6cea

[Feat(user)/#72] 가게 여러건 조회 api 연동

---

lib/user/screens/storeselect_screen.dart

[fix : #77] : 파일 이름 수정

---

lib/owner/models/menu_model.dart
lib/user/models/cartMenu_model.dart
lib/user/screens/cart_screen.dart
lib/user/screens/menuselect_screen.dart
lib/user/screens/storeselect_screen.dart
lib/user/screens/userReview_screen.dart
lib/user/screens/write_screen.dart
lib/user/services/cart_service.dart
lib/user/widgets/cart_widget.dart

#83
- 장바구니 메뉴 모델을 따로 생성해서 조회 api 연동
Uploading Simulator Screen Recording - iPhone 14 Pro Max(배달반도) - 2024-06-07 at 00.44.11.mp4…

[Feat(user)/#83] 장바구니 조회 api 연동

---

ios/Podfile.lock
ios/Runner.xcodeproj/project.pbxproj
ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
lib/all/screens/login_screen.dart
lib/owner/models/menu_model.dart
lib/owner/screens/addMenu_screen.dart
lib/owner/screens/home_screen.dart
lib/owner/screens/register_store.dart
lib/owner/services/menu_service.dart
pubspec.lock

#81 
- StoreService().registerStore 안의 정보를 context에 담아서 true 값으로 가게 등록 시 바로 홈페이지로 이종
- showModalBottomSheet가 반환하는 Future<bool>을 받아와서 refresh 변수에 담고 refresh가 true일 경우 상태를 갱신하여 Bottomsheet를 매번 새로고침

[Feat(owner)/#81] 가게나 메뉴 등록 시 UI 수정

---

lib/owner/screens/letter_screen.dart
lib/owner/screens/receipt_screen.dart

#86 
- 주문을 완료 상태로 설정하는 completeOrder 메서드 사용하여 orderList[index]['isCompleted'] = true로 적용
https://github.com/C-S-A-I-CommentScribeAI/frontend/assets/136067544/586626e4-6462-4ccf-bbec-2323f3384bf4

[feat : #86] 출력하기 버튼 클릭 시 배달완료 UI 수정

---

lib/owner/screens/letter_screen.dart
lib/owner/screens/receipt_screen.dart
lib/owner/services/delivery_service.dart
lib/owner/services/letter_service.dart

#91 
- List 타입이 아니라 String 타입으로 변경 --> 편지 저장 api
- letterController에 불러온 편지 내용 설정 --> 주문 수락 후 편지 생성 api
- 주문 수락 버튼 클릭 시 LetterService().saveLetter() 값을 isSaved 변수에 저장
- isSaved 값이 true이면 3초 후에 상태를 배차 / 출력 버튼으로 변경
- 출력하기 버튼을 클릭했을 때 orderId 값에 따라 DeliveryService().completeDelivery() 객체방식으로 매서드에 접근하여 적용 --> 배달완료api 연동

[Feat(owner)/#91] 편지 저장 & 주문 수락 후 편지 생성 & 배달 완료 API 연동

---

ios/Podfile.lock
ios/Runner.xcodeproj/project.pbxproj
ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
lib/all/screens/login_screen.dart
lib/main.dart
lib/user/models/orderMenu_model.dart
lib/user/models/order_model.dart
lib/user/screens/cart_screen.dart
lib/user/screens/complete_screen.dart
lib/user/screens/userOrder_screen.dart
lib/user/services/cart_service.dart
lib/user/services/order_service.dart

#90
- 주문 조회 api 연동
Uploading Simulator Screen Recording - iPhone 14 Pro Max(배달반도) - 2024-06-08 at 04.01.36.mp4…

[Feat(user)/#90] 주문 조회 api 연동

---

lib/all/services/order_service.dart
lib/owner/screens/home_screen.dart
lib/owner/screens/receipt_screen.dart
lib/user/models/order_model.dart

#95
- 엔드포인트의 storeId를 가게 여러건 조회 api에서 가져옴
- await getStoreId() 작성할 때 FutureBuilder안에 await 사용할 수 없기 때문에
- FutureBuilder의 future를 반환하는 함수 생성

[Feat(owner)/#95] 사장님 주문 조회 API 연동

---

ios/Podfile.lock
lib/owner/screens/home_screen.dart
lib/owner/screens/review_screen.dart
lib/user/screens/write_screen.dart
lib/user/services/review_service.dart
pubspec.lock

#99 
- 리뷰 작성자의 닉네임, 리뷰 평점, 리뷰 코멘트, 메뉴 항목, 답글 달기 버튼 생성
- Spacer() PopupMenuButton을 오른쪽에 배치

[feat(all) : #99] 가계별 가게 리뷰 API 연동

---

lib/user/screens/userHome_screen.dart
lib/user/services/selectCategory_service.dart
lib/user/services/userStore_service.dart

#102
- Map<String, String> categoryTranslations 즉, 영어 카테고리를 한글로 변환하는 맵을 만들어 설정

[fix(user)/#102] : 고객 홈화면 카테고리 한글로 수정

---

lib/all/screens/login_screen.dart
lib/owner/screens/home_screen.dart

#104 
- 필요없는 메뉴 삭제
- childAspectRatio 속성으로 Gridview 위젯 높이 조절
- userRole에 따라 페이지 이동 다르게 처리
https://github.com/C-S-A-I-CommentScribeAI/frontend/assets/136067544/a1fb6f65-3080-4e15-9f28-bbf0b1fcd67e
https://github.com/C-S-A-I-CommentScribeAI/frontend/assets/136067544/ecd75ed4-e4fa-4598-8765-5e35fc1aa1d5

[fix(all) : #104] UserRole에 따라 홈화면 페이지 이동 수정

---

ios/Podfile.lock
lib/owner/screens/letter_screen.dart
linux/flutter/generated_plugin_registrant.cc
linux/flutter/generated_plugins.cmake
macos/Flutter/GeneratedPluginRegistrant.swift
pubspec.lock
pubspec.yaml
windows/flutter/generated_plugin_registrant.cc
windows/flutter/generated_plugins.cmake

feat(owner) : #107 핸드폰과 앱 사의 블루투스 연결하기

---

lib/main.dart
lib/owner/providers/store_provider.dart
lib/owner/screens/home_screen.dart
lib/owner/screens/letter_screen.dart
lib/owner/screens/review_screen.dart
lib/owner/screens/store_screen.dart
lib/owner/services/store_service.dart
pubspec.yaml

#112
- List<StoreModel> 타입의 가게 조회 api를 호출해 getStoreList에 저장
- Provider 파일에서 _storeList에 저장
- storepage는 storeID만 받기로 수정
- 가게 조회 응답데이터에 사업자 등록 번호가 없어서 제거

[Feat(owner)/#112] 가게 등록, 조회(사장님) API 및 Provider 구현

---

lib/main.dart
lib/owner/models/store_model.dart
lib/owner/providers/menu_provider.dart
lib/owner/screens/addMenu_screen.dart
lib/owner/screens/home_screen.dart
lib/owner/screens/menu_screen.dart
lib/owner/services/menu_service.dart

[Feat(owner)/#114] 가게별 메뉴 조회 api 및 provider 구현

---

lib/all/services/order_service.dart
lib/main.dart
lib/owner/providers/letter_provider.dart
lib/owner/providers/order_provider.dart
lib/owner/screens/letter_screen.dart
lib/owner/screens/orderDetail_screen.dart
lib/owner/screens/receipt_screen.dart
lib/owner/services/delivery_service.dart
lib/owner/services/letter_service.dart

#121
- 수락 버튼을 누르면 isCooking가 true가 되어 조리 중으로 변하고 api가 성공되면 다시 false가 됨
- api가 성공되면 orderStatus가 Delivered로 바껴 배차/출력 버튼으로 변경되게 작성
- api 성공 시간에 따라 조리 중으로 뜨는 시간이 달라짐
- orderDetail의 내용들을 receipt 페이지로 이동
- Provider를 통해서 편지 내용을 가져옴

[Feat(owner)/#121] 주문 조회 & 수락 및 편지작성 후 저장, 편지 불러오기, 배달 완료 api 구현하기

---

lib/all/widgets/userReview_widget.dart
lib/main.dart
lib/owner/screens/review_screen.dart
lib/user/models/order_model.dart
lib/user/providers/review_provider.dart
lib/user/providers/userOrder_provider.dart
lib/user/screens/complete_screen.dart
lib/user/screens/menuselect_screen.dart
lib/user/screens/userHome_screen.dart
lib/user/screens/userReview_screen.dart
lib/user/screens/write_screen.dart
lib/user/services/review_service.dart
lib/user/services/userOrder_service.dart
lib/user/widgets/orderAndPay_widget.dart

#123
- orderModel key 값 추가
- userHome페이지에서 마이페이지 제거하고 주문 내역 페이지로 이동하는 아이콘 구현

[Feat(user)/#123] 주문 조회, 리뷰 작성, 가게 리뷰 조회 api 구현
